name: Tidy3d Pre-Release

# on:
  # push:
  #   tags:
  #     - 'v*.*.*-pre-release+*'

on:
  workflow_dispatch:
  push:
    branches: [ feature/pre-release-workflow ]
  pull_request:
    branches: [ feature/pre-release-workflow ]

jobs:
  echo-from-prerelease-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: pre/1.9.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo "running pre-release workflow from branch: "
        echo ${{ github.ref_name }}
        echo ${{ github.ref }}
        echo ${{ github.head_ref }}
